# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
# Enable C++ support
language: cpp
# Build steps
script:
  - make
  -  echo '<2: 1.18973e+4932 1.18973e+4932 >' | ./cwk
  -  echo '<6: 7 11 2 13 3 5 >' | ./cwk
  -  echo '<6: 7 11 2 13 3 5 >' | ./cwkt
